# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJB8uG_zq0jnY_Ccfyp8Zl0h1JelSMm1
"""

#drive.mount('/content/drive')
import pandas as pd
import numpy as np
data=pd.read_csv("/content/Feature extraction sentence_contradiction.csv")

from sklearn.preprocessing import StandardScaler

x=StandardScaler().fit_transform(data)

x

mean=np.mean(x,axis=0)
cov_mat=(x-mean).T.dot((x-mean))/(x.shape[0]-1)

cov_mat

cova_mat=np.cov(x.T)

cova_mat

eig_val,eig_vect=np.linalg.eig(cova_mat)

eig_val

eig_vect

eig_pairs=[(np.abs(eig_val[i]),eig_vect[:,i]) for i in range(len(eig_val))]

for i in eig_pairs:
  print(i[1])

from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca.fit_transform(data)
print(pca.explained_variance_ratio_)

pca=PCA(n_components=2)
pca.fit_transform(x)
print(pca.explained_variance_ratio_)

#explained variance
from matplotlib import pyplot as plt
pca=PCA().fit(x)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.show()

